- name: install nginx and run
  hosts: web
  become: yes #refer root
  tasks:
    -name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

    -name: run nginx
    ansible.builtin.package:
      name: started
      state: started
      enabled: yes
